site_name: Orbit Python Kütüphanesi

theme:
  language: tr
  name: material
  palette:
    scheme: slate
    primary: indigo
  font:
    text: Roboto
    size: 12
  logo: assets/orbit_icon.png
  favicon: assets/orbit_icon.png

  features:
    - content.code.copy
    - content.admonitions
    - navigation.footer

plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      locale: tr
      handlers:
        python:
          options:
            show_source: false
  - search
nav:
  - Orbit Kodlama Seti Dökümantasyonu: index.md
  - Temel Seviye: temel_seviye.md
  - Orbit Python:
      - Orbit Python: python-docs/python_index.md
      - Başlarken: python-docs/getting-started.md
      - Robotik programlama: python-docs/robotic-programming.md
      - Orbit AI: python-docs/orbit-ai.md
      - API Referansı: python-docs/reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      pygments_style: monokai

  - pymdownx.extra
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
