site_name: Orbit Python Kütüphanesi

theme:
  language: tr
  name: material
  palette:
    scheme: slate
    primary: indigo
  font:
    text: Roboto
    size: 12
  logo: assets/orbit_icon.png
  favicon: assets/orbit_icon.png

  features:
    - content.code.copy
    - content.admonitions
    - navigation.footer

plugins:
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      locale: tr
      handlers:
        python:
          options:
            show_source: false
  - search
nav:
  - Orbit Kodlama Seti Dökümantasyonu: index.md
  - Kullanım Kılavuzu : kullanma_kilavuzu.md
  - Web Sitesi: 
    - Öğretmen ve Öğrenci Paneli: temel_seviye.md
    - Orta Seviye Görev : medium_task.md
    
  - Python 101:
    - Öğretmen için Konular ve Örnek Uygulamaları:
      - Değişken ve Veri Türleri: python-egitimi-konu-anlatim/degisken_veri_turleri.md
      - Strings: python-egitimi-konu-anlatim/strings.md
      - Numbers : python-egitimi-konu-anlatim/numbers.md
      - Lists : python-egitimi-konu-anlatim/lists.md
      - Logical Conditions and Booleans :  python-egitimi-konu-anlatim/logical_booleans.md
      - If Statements : python-egitimi-konu-anlatim/if_statements.md
      - Loops:  python-egitimi-konu-anlatim/loops.md
      - Range : python-egitimi-konu-anlatim/range.md
      - Functions : python-egitimi-konu-anlatim/functions.md
    - Öğrenci Örnek Uygulamaları : python-egitimi-konu-anlatim/student_applications.md
   
      
      


  - Orbit Python:
      - Orbit Python: python-docs/python_index.md
      - Başlarken: python-docs/getting-started.md
      - Robotik programlama: python-docs/robotic-programming.md
      - Orbit AI: python-docs/orbit-ai.md
      - API Referansı: python-docs/reference.md
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      pygments_style: monokai
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - tables
  - fenced_code
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.blocks.html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


docs_dir: docs